#ifndef pqCoreInit_h
#define pqCoreInit_h

#include "pqCoreModule2.h"

/**
 * pqCoreInit() is for initializing QT resources. When pqCore is built
 * as a static library, linkers may drop out entire object
 * files such as files generated by rcc. Client apps can call to use Qt
 * resources outside PV.
 */

PQCORE_EXPORT void pqCoreInit();

#endif
