#ifndef pqWidgetsInit_h
#define pqWidgetsInit_h

#include "pqWidgetsModule2.h"

/**
 * pqWidgetsInit() is for initializing QT resources. When pqWidgets is built
 * as a static library, linkers may drop out entire object
 * files such as files generated by rcc. Client apps can call to use Qt
 * resources outside PV.
 */

PQWIDGETS_EXPORT void pqWidgetsInit();

#endif
